### ISSUE TITLE
Create ViewSet: SavePosts

### ISSUE THREAD

**Issue by calebwagner** [calebwagner/uteach-ilearn-server#12]
**TODO:**

- [ ] get function
- [ ] post function with @api_view(['POST'])
- [ ] import to `init file`
- [ ] add url path
